version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - static_volume:/app/static  # Для статических файлов (опционально)
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume:  # Удалите, если не используете статические файлы
