version: '3.8'
services:
  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 158.160.84.43:8000 autoparking.wsgi"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
    ports:
      - "80:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - autoparking_network
volumes:
  static_volume:
networks:
  autoparking_network:
