# Generated by Django 4.2.1 on 2023-06-02 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myparking', '0002_remove_car_parking_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='cars',
            field=models.ManyToManyField(blank=True, help_text='Select a car for this parking', null=True, to='myparking.car'),
        ),
    ]
