# Generated by Django 4.2.1 on 2023-06-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0006_rename_user_payment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='receipt_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot', to='myparking.parkingspot'),
        ),
        migrations.AddField(
            model_name='payment',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
