# Generated by Django 4.2.1 on 2023-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0010_remove_account_client_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='date_of_rent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
