# Generated by Django 4.2.1 on 2023-09-11 12:02

from django.db import migrations, models
import myparking.models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0011_parkingspot_date_of_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=myparking.models.upload_to_news_image)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
