# Generated by Django 4.2.1 on 2023-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0014_banner_bannerinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_usage_count', models.PositiveIntegerField()),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
