# Generated by Django 4.2.1 on 2023-06-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0004_alter_payment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='user',
        ),
    ]
