# Generated by Django 4.2.1 on 2023-06-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0005_rename_client_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
    ]
