# Generated by Django 4.2.1 on 2023-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0007_rename_date_payment_receipt_date_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='repayment_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
