# Generated by Django 4.2.1 on 2023-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0008_payment_receipt_time_payment_repayment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='repayment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
