# Generated by Django 4.2.1 on 2023-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/banner/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BannerInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_seconds', models.PositiveIntegerField(default=3000)),
            ],
        ),
    ]
