name: SAST with CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python  # Уточнить язык проекта

    - name: Perform Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "SAST_Report"

    - name: Generate Human-Readable Report
      run: |
        echo "## CodeQL Findings" > report-sast.md
        jq -r '.runs[0].results[] | "### \(.message.text)\nFile: \(.locations[0].physicalLocation.artifactLocation.uri)\nLine: \(.locations[0].physicalLocation.region.startLine)"' codeql-results.sarif >> report-sast.md

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: sast-report
        path: report-sast.md
